[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "python3 -m playwright install-deps chromium", "python3 -m playwright install chromium"]

[start]
cmd = "python3 start.py"
